name: aplikasi_peminjaman
description: "A project for Tool Lending System SMK Brantas Karangkates"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # --- KONEKSI DATABASE (SUDAH DITAMBAHKAN) ---
  # Ini adalah 'kabel' untuk menghubungkan Flutter dengan Tabel Supabase Mas
  supabase_flutter: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Jika Mas punya gambar logo, aktifkan bagian assets di bawah ini:
  # assets:
  #   - assets/images/